server:
  port: '@server.port@'
---
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always
---
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
      jdbc-url: @db.url@
      username:  @db.user@
      password: @db.password@
      driver-class-name: org.postgresql.Driver
  flyway:
      url: "jdbc:postgresql://localhost:5432/ch_notificator"
---
info:
  version: '@project.version@'
  stage: dev
mail:
  host: mr1.linode.rbkmoney.net
  port: 25
  username: ""
  password: ""
  from: no-reply@rbkmoney.com
  protocol: smtp
  retry:
    max:
      attempts: 3
    backoff:
      period: 1000
  smtp:
    auth: false
    timeout: 30000
    starttls:
      enable: true
---
clickhouse.db:
  url: "jdbc:clickhouse://localhost:8123/default"
  user: "user"
  password: "password"
  connection.timeout: 50000
  compress: false