server:
  port: '@server.port@'
  rest:
    port: '@server.rest.port@'
    endpoint: ch-manager
---
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always
---
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    flyway:
        url: "jdbc:postgresql://localhost:5432/ch_notificator"
---
info:
  version: '@project.version@'
  stage: dev
mail:
  host: mr1.linode.rbkmoney.net
  port: 25
  username: ""
  password: ""
  from: no-reply@rbkmoney.com
  protocol: smtp
  retry:
    max:
      attempts: 3
    backoff:
      period: 1000
  smtp:
    auth: false
    timeout: 30000
    from-address: "NotificationService@rbkmoney.com"
    starttls:
      enable: true
---
clickhouse.db:
  url: "jdbc:clickhouse://localhost:8123/default"
  user: "user"
  password: "password"
  connection.timeout: 50000
  compress: false
---
swagger:
  paths: |
    /swagger-ui.html,
    /webjars/springfox-swagger-ui/**/*,
    /swagger-resources,
    /swagger-resources/**/*,
    /v2/api-docs
